"""Change pessoa_id to people_id

Revision ID: ebbc9391d343
Revises: 2d557030e802
Create Date: 2021-08-10 11:43:12.705204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbc9391d343'
down_revision = '2d557030e802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_pessoa_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'people', ['person_id'], ['id'])
    op.drop_column('users', 'pessoa_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pessoa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_pessoa_id_fkey', 'users', 'people', ['pessoa_id'], ['id'])
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###
